---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          rfc2136:
            nameserver: "${PRIVATE_DNS_PRIMARY}"
            tsigKeyName: externaldns
            tsigAlgorithm: hmac-sha256
            tsigSecretSecretRef:
              name: dns_tsig_key
              key: SECRET_TSIG_KEY
        selector:
          dnsZones:
            - ${SECRET_DOMAIN}
