# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: dns_tsig_key
    namespace: kube-system
stringData:
    SECRET_TSIG_KEY: ENC[AES256_GCM,data:yU/S9sFueQAypLmpT1ZrsFzL2YDjf4fYhN8HVevJI6FI91Ypgx6mLyg2ltE=,iv:hvlEQr8KGDC5ZRr1keIIqbYsotmnACjcpCLNPOl9X/w=,tag:3l7GI1ra/a1ztQYVxt4+7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7hhqxzl3xkmlhk0d25k2eapsv8sl80m995y7hatgcjm85v8zaqqme3qhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOUV5V1BkY3VFbnh6d0Jl
            czJ1TG1lMDRTUTRFb1JRU2FNUU1Fc01xdm5NClFDWjErcEp3M0wxckJmSXE0WlQy
            cWQ3RlNOV2tjYU1tRjN0eDhlcTJzM0kKLS0tIFNtdzFkbnQ0eFI5anl0QXVsaFZL
            andSV1pGbHdka3FyNFdLYnM4R3VsZU0Kn15hLplVGV+3BUR0ToM9cADQIVw7Yrqd
            57iib4iZumT/GbiknrFub+XjZg7wLEtUxu6H8n8ro835mOfvmZlIng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-01T10:41:58Z"
    mac: ENC[AES256_GCM,data:OoPmfRz5ZTMR1+dQ2Xwd14ahNgtmX8RNoui+mj2Erx1xDMz8gG/4hoYeLVHxAq3N8hz59MrU1fm6vIQOOkvQe44qC1DA+rQULXc9dOV9nDzUF5+w7SfcUTGQt39O+Hln/V8J4DBrq6ooiP4ftnQckdk99q7ahccNRbF/CNsjyw8=,iv:RxBNTjiAMVGvKKEhZ+RhFJ3wfgmQZrEAf+2xibYcpHA=,tag:FWvOyXINuhQOmaa0LmaMOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
