# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: dns_tsig_key
    namespace: kube-system
data:
    SECRET_TSIG_KEY: ENC[AES256_GCM,data:H9FXgJoiEbryJnLo4uYB+/DZ/Fnhqr7rC8/KIXC2e3rJg0vZR1LbKfgY8hrCzedRf9kVCTKTBPwaTvIq,iv:GpD7zPyheAOwAIADChYiJgqtArDHz+RqPrj86aBmraM=,tag:TzB1mPPFjTFZxrGmxXNrEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7hhqxzl3xkmlhk0d25k2eapsv8sl80m995y7hatgcjm85v8zaqqme3qhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOUV5V1BkY3VFbnh6d0Jl
            czJ1TG1lMDRTUTRFb1JRU2FNUU1Fc01xdm5NClFDWjErcEp3M0wxckJmSXE0WlQy
            cWQ3RlNOV2tjYU1tRjN0eDhlcTJzM0kKLS0tIFNtdzFkbnQ0eFI5anl0QXVsaFZL
            andSV1pGbHdka3FyNFdLYnM4R3VsZU0Kn15hLplVGV+3BUR0ToM9cADQIVw7Yrqd
            57iib4iZumT/GbiknrFub+XjZg7wLEtUxu6H8n8ro835mOfvmZlIng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-01T12:53:41Z"
    mac: ENC[AES256_GCM,data:ZppUE9QzJV+Ikm/lAjUxIF4i45LJwzwX08yvoZweCWZyaINzmRI3c38AFM3pteevUqcj6ri9A0BEPdW+YD1HPebv4NsyY38lAeNS+RA1bMMs8bBLx22iNQ5bb7Mc9nDD6W6ikbSpZnsOszYnzYIrwrXiMYaNeaRnw2E9XmitJTo=,iv:U7jJf6UvVffzHBTk3n/7MDthLYn2YrnPgw2pgKpGIhM=,tag:GDvfPeZXQz3ks9zW/ldCOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
