---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/London
  METALLB_LB_RANGE: 10.42.73.161-10.42.73.167
  METALLB_K8S_GATEWAY_ADDR: 10.42.73.161
  METALLB_TRAEFIK_ADDR: 10.42.73.162
