---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cert-manager
      version: v1.8.2
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    installCRDs: false
    webhook:
      enabled: true
    extraArgs:
      - --dns01-recursive-nameservers=148.88.65.52:53,148.88.65.53:53
      - --dns01-recursive-nameservers-only
    replicaCount: 1
    podDnsPolicy: "None"
    podDnsConfig:
      nameservers:
        - "148.88.65.52"
        - "148.88.65.53"
