---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: internal-dns
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 5

  values:
    nameOverride: internal-dns
    logLevel: debug
    provider: rfc2136

    extraArgs:
      - --rfc2136-host=${PRIVATE_DNS_PRIMARY}
      - --rfc2136-port=53
      - --rfc2136-zone=${SECRET_DOMAIN}
      - --rfc2136-min-ttl=0s
      - --rfc2136-tsig-axfr
      - --rfc2136-tsig-keyname=externaldns
      - --rfc2136-tsig-secret-alg=hmac-sha256
      - --rfc2136-tsig-secret=${SECRET_TDIG}

    podAnnotations:
      secret.reloader.stakater.com/reload: internal-dns

    policy: sync

    sources:
      - service
      - ingress

    domainFilters:
      - "${SECRET_DOMAIN}"

    txtOwnerId: "default"


    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 250Mi
