# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: internal-dns
    namespace: networking
    labels:
        app.kubernetes.io/name: internal-dns
        app.kubernetes.io/instance: internal-dns
type: Opaque
data:
    rfc2136_tsig_secret: ENC[AES256_GCM,data:GDSr2JoeiBFDBShpjIs6qFagCBdY6IxwDQtuKflt2KRoE1bAJ/vt2ctaiVw=,iv:DREBCv5U2OLe96ME1ZAwVCLKRaAsMmtCya25YuyDiqQ=,tag:JSEtswn3nQYZQcqMqeMm/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7hhqxzl3xkmlhk0d25k2eapsv8sl80m995y7hatgcjm85v8zaqqme3qhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZUdkWGNwTnptNUlyVUZT
            WG9Mcnh2TzRmMzYvSmdMUDNXeHZJRys2NGhFClBMR3pYVDNsaDRFc3Jkb2l0L2hU
            cExGbFNMK0M1Z0dyNm5hV21yaWtxd0UKLS0tIEhDckk3MHoyMW5XSjlwY2RmemNx
            RXNuUFcyWUdLVzhJQVZocThlVFdzVkEKQNgA0x1heV1pVqagw+8V099yskq+k97E
            bZ8nSm7LeLnLxnbDmUnhhz8+NPu7vKx207V9X0qyO34Udaq3+sZn1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-30T21:16:26Z"
    mac: ENC[AES256_GCM,data:MhsKE9JcpfBEahQLXUky5qUwXBVVB0wgdMdciF8fTX4BcSwji0ytHouXGg5JyVKj+mSxBADygLJTZDaPd79R6PliT6OwbRoCH/meZmzeVofhmun1UPBK6gELmDABwBgzIujEjrpyt4cRsqCzhNM2qSjY/118dHjL5UV10ByQaBM=,iv:MTrWsppxxcvJW6uscenJEHkeOYEqtL+piUhHKLkilfI=,tag:byQ7OJRK7uORfQiEHqRl9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
